### ISSUE TITLE
登录用户：个人功能分区

### ISSUE THREAD

**Issue by qaqland** [moobu/obs-design#1]
分类和邮箱、动态有点接近

- 【关注】类似于qq空间动态
- 【未读】这个需要吗？感觉可要可不要
- 【收藏】star、收藏夹
- 【归档】回收站

这是个流程问题：

1. 【关注】的是人和标签？【未读】是阅读清单、手动或者自动生成的RSS？
2. 什么样的网址需要被归档（比如，这个文章我已经不需要了）

**Comment by qaqland** [comment]
@mivinci 以后就在这里吧，不用开其他平台了

**Comment by mivinci** [comment]
好 但发 discussion 好些

**Comment by qaqland** [comment]
可恶！那里没这里简洁直观！！

**Comment by mivinci** [comment]
能用就行 不过我感觉挺清晰的

**Comment by qaqland** [comment]
【未读】这个词可以换成 【Inbox】、【通知】等，主要给 **bot 插件** 生成其他平台更新消息的自由空间
